AUGMENT_WITH_3D_SCALE: false
BALANCE_3D_DATASETS: false
CHECKPOINT_PERIOD: 144
CUDNN_BENCHMARK: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: true
  NUM_WORKERS: 4
  REPEAT_SQRT: true
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
  TEST_NUM_WORKERS: 4
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
  - strawberry_val
  TEST_2D_ONLY: []
  TEST_3D_ONLY: []
  TEST_SUBSAMPLED: []
  TRAIN:
  - strawberry_train
  TRAIN_2D: []
  TRAIN_3D: []
DECODER_NUM_LAYERS: 1
DEPTH_PREFIX: depth_inpainted
DISABLE_SHUFFLE: true
DO_ELASTIC_DISTORTION: false
DO_FLIPPING: false
DO_ROT_SCALE: true
DO_TRILINEAR_INTERPOLATION: true
EVALUATE_SUBSET: null
EVAL_PER_IMAGE: false
EXPORT_BENCHMARK_DATA: false
EXPORT_BENCHMARK_PATH: null
FEATURE_VIS: false
FIND_UNUSED_PARAMETERS: false
FLOAT32_PRECISION: ''
GLOBAL:
  HACK: 1.0
HIGH_RES_INPUT: false
HIGH_RES_SUBSAMPLE: false
IGNORE_DEPTH_MAX: -1.0
INPUT:
  AUGMENTATIONS: []
  AUGMENT_3D: true
  CAMERA_DROP: true
  CHUNK_AUG_MAX: 5
  COLOR_AUG: true
  COLOR_AUG_SSD: true
  CROP:
    ENABLED: false
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE:
    - 640
    - 640
    TYPE: absolute
  DATASET_MAPPER_NAME: scannet
  FORMAT: RGB
  FRAME_LEFT: 1
  FRAME_LEFT_2D: 2
  FRAME_RIGHT: 1
  FRAME_RIGHT_2D: 2
  IMAGE_SIZE: 640
  IMAGE_SIZE_2D: 1024
  INPAINT_DEPTH: true
  MASK_FORMAT: polygon
  MAX_SCALE: 2.0
  MAX_SIZE_TEST: 640
  MAX_SIZE_TEST_2D: 1333
  MAX_SIZE_TRAIN: 640
  MIN_SCALE: 0.1
  MIN_SIZE_TEST: 640
  MIN_SIZE_TEST_2D: 800
  MIN_SIZE_TEST_SAMPLING: choice
  MIN_SIZE_TRAIN:
  - 640
  MIN_SIZE_TRAIN_SAMPLING: choice
  ORIGINAL_EVAL: false
  RANDOM_FLIP: none
  SAMPLE_CHUNK_AUG: false
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_NUM_2D: 5
  SIZE_DIVISIBILITY: 32
  STRONG_AUGS: true
  UNIFORM_SAMPLE: false
  VOXELIZE: false
  VOXEL_SIZE:
  - 0.02
  - 0.04
  - 0.08
  - 0.16
INTERP_NEIGHBORS: 8
JUST_DUMP_PREDS: false
KNN_THRESH: 0.001
MATTERPORT_ALL_CLASSES_TO_21: false
MATTERPORT_DATA_DIR: /projects/katefgroup/language_grounding/mask3d_processed/matterport/train_validation_database.yaml
MAX_FRAME_NUM: 5
MAX_TIME_HOURS: 6.0
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - -90
      - 0
      - 90
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES:
    - - 32
      - 64
      - 128
      - 256
      - 512
  BACKBONE:
    FREEZE_AT: 0
    NAME: build_resnet_backbone
  BAYESIAN_INFERENCE_DURING_TRAINING: true
  BAYESIAN_SAMPLES: 1
  BAYESIAN_TYPE: swag
  CROSS_VIEW_BACKBONE: false
  CROSS_VIEW_CONTEXTUALIZE: true
  CROSS_VIEW_NUM_LAYERS:
  - 2
  - 2
  - 6
  - 2
  CROSS_VIEW_NUM_LAYERS_ENCODER_TIED: 3
  DECODER_2D: false
  DECODER_3D: true
  DECODER_ONLY_PANET: false
  DECODER_PANET: false
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES: []
    NORM: ''
    OUT_CHANNELS: 256
  FREEZE_BACKBONE: false
  INTERPOLATION_METHOD: nearest
  KEYPOINT_ON: false
  KNN: 8
  LANG_FREEZE_BACKBONE: true
  LOAD_PROPOSALS: false
  MASK_FORMER:
    CLASS_WEIGHT: 2.0
    DEC_LAYERS: 10
    DEEP_SUPERVISION: true
    DICE_WEIGHT: 5.0
    DIM_FEEDFORWARD: 2048
    DROPOUT: 0.0
    ENC_LAYERS: 0
    ENFORCE_INPUT_PROJ: false
    HIDDEN_DIM: 256
    IMPORTANCE_SAMPLE_RATIO: 0.75
    MASK_WEIGHT: 5.0
    NHEADS: 8
    NON_PARAM_QUERY: false
    NO_OBJECT_WEIGHT: 0.1
    NUM_OBJECT_QUERIES: 20
    OVERSAMPLE_RATIO: 3.0
    PRE_NORM: false
    SIZE_DIVISIBILITY: 32
    TEST:
      INSTANCE_ON: true
      OBJECT_MASK_THRESHOLD: 0.8
      OVERLAP_THRESHOLD: 0.8
      PANOPTIC_ON: false
      SEMANTIC_ON: false
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: false
    TRAIN_NUM_POINTS: 12544
    TRAIN_NUM_POINTS_2D: 12544
    TRANSFORMER_DECODER_NAME: ODINMultiScaleMaskedTransformerDecoder
    TRANSFORMER_IN_FEATURE: multi_scale_pixel_decoder
  MASK_ON: true
  MAX_SEQ_LEN: 256
  META_ARCHITECTURE: ODIN
  NO_DECODER_PANET: false
  OPEN_VOCAB: false
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: true
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_DECODER_PANET: false
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.12
  - 57.375
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    RES2_OUT_CHANNELS: 256
    RES4_DILATION: 1
    RES5_DILATION: 1
    RES5_MULTI_GRID:
    - 1
    - 1
    - 1
    STEM_OUT_CHANNELS: 64
    STEM_TYPE: basic
    STRIDE_IN_1X1: false
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS: &id002
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES:
    - p3
    - p4
    - p5
    - p6
    - p7
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.4
    - 0.5
    NMS_THRESH_TEST: 0.5
    NORM: ''
    NUM_CLASSES: 80
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS:
    - &id001
      - 10.0
      - 10.0
      - 5.0
      - 5.0
    - - 20.0
      - 20.0
      - 10.0
      - 10.0
    - - 30.0
      - 30.0
      - 15.0
      - 15.0
    IOUS:
    - 0.5
    - 0.6
    - 0.7
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: *id001
    CLS_AGNOSTIC_BBOX_REG: false
    CONV_DIM: 256
    FC_DIM: 1024
    FED_LOSS_FREQ_WEIGHT_POWER: 0.5
    FED_LOSS_NUM_CLASSES: 50
    NAME: ''
    NORM: ''
    NUM_CONV: 0
    NUM_FC: 0
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: false
    USE_FED_LOSS: false
    USE_SIGMOID_CE: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES:
    - res4
    IOU_LABELS:
    - 0
    - 1
    IOU_THRESHOLDS:
    - 0.5
    NAME: Res5ROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 80
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: true
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: false
    CONV_DIM: 256
    NAME: MaskRCNNConvUpsampleHead
    NORM: ''
    NUM_CONV: 0
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS: *id002
    BOUNDARY_THRESH: -1
    CONV_DIMS:
    - -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES:
    - res4
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.3
    - 0.7
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 6000
    PRE_NMS_TOPK_TRAIN: 12000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    ASPP_CHANNELS: 256
    ASPP_DILATIONS:
    - 6
    - 12
    - 18
    ASPP_DROPOUT: 0.1
    COMMON_STRIDE: 4
    CONVS_DIM: 256
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES:
    - res3
    - res4
    - res5
    DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
    IGNORE_VALUE: 255
    IN_FEATURES:
    - res2
    - res3
    - res4
    - res5
    LOSS_TYPE: hard_pixel_mining
    LOSS_WEIGHT: 1.0
    MASK_DIM: 256
    NAME: ODINHead
    NORM: GN
    NO_SKIP_CONN: false
    NUM_CLASSES: 3
    PIXEL_DECODER_NAME: MSDeformAttnPixelDecoder
    PROJECT_CHANNELS:
    - 48
    PROJECT_FEATURES:
    - res2
    TRANSFORMER_ENC_LAYERS: 6
    USE_DEPTHWISE_SEPARABLE_CONV: false
  SUPERVISE_SPARSE: false
  SWAG:
    MAX_MODELS: 10
    NO_COV_MAT: false
    RANK: 20
    SCALE: 1.0
    START_EPOCH: 3
    UPDATE_FREQ: 5
  SWIN:
    APE: false
    ATTN_DROP_RATE: 0.0
    DEPTHS:
    - 2
    - 2
    - 6
    - 2
    DROP_PATH_RATE: 0.3
    DROP_RATE: 0.0
    EMBED_DIM: 96
    MLP_RATIO: 4.0
    NUM_HEADS:
    - 3
    - 6
    - 12
    - 24
    OUT_FEATURES:
    - res2
    - res3
    - res4
    - res5
    PATCH_NORM: true
    PATCH_SIZE: 4
    PRETRAIN_IMG_SIZE: 224
    QKV_BIAS: true
    QK_SCALE: null
    USE_CHECKPOINT: false
    WINDOW_SIZE: 7
  WEIGHTS: my_odin/models/odin_scannet_context.pth
MULTI_TASK_TRAINING: false
NAN_LR_SCALE: 0.1
NAN_RECOVERY_ENABLED: true
NAN_RECOVERY_ITERS: 100
NON_PARAM_SOFTMAX: false
OUTPUT_DIR: ./output
PROB: null
RANDOM_SELECT_CLASSES: false
REPEAT_S3DIS: false
S3DIS_DATA_DIR: /projects/katefgroup/language_grounding/SEMSEG_100k/s3dis/train_validation_database.yaml
SAMPLED_CROSS_ATTENTION: true
SAMPLE_SIZES:
- 800
- 3200
- 12800
SAMPLING_STRATEGY: consecutive
SCANNET200_DATA_DIR: /projects/katefgroup/language_grounding/mask3d_processed/scannet200/train_validation_database.yaml
SCANNETPP_DATA_DIR: null
SCANNET_DATA_DIR: /projects/katefgroup/language_grounding/mask3d_processed/scannet/train_validation_database.yaml
SEED: -1
SKIP_CLASSES: null
SKIP_CLASSES_2D: null
SOLVER:
  AMP:
    ENABLED: true
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR: 0.0001
  BASE_LR_END: 0.0
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 144
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 0.1
    ENABLED: true
    NORM_TYPE: 2.0
  GAMMA: 0.1
  IMS_PER_BATCH: 1
  IMS_PER_BATCH_2D: 16
  IMS_PER_BATCH_3D: 16
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 11680
  MOMENTUM: 0.9
  NESTEROV: false
  NUM_DECAYS: 3
  OPTIMIZER: ADAMW
  POLY_LR_CONSTANT_ENDING: 0.0
  POLY_LR_POWER: 0.9
  REFERENCE_WORLD_SIZE: 0
  RESCALE_INTERVAL: false
  STEPS:
  - 8175
  - 10512
  TEST_IMS_PER_BATCH: 1
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: null
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4000
    MIN_SIZES:
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
  DETECTIONS_PER_IMAGE: 100
  EVAL_2D: false
  EVAL_3D: true
  EVAL_PERIOD: 144
  EVAL_SPARSE: false
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
  SUBSAMPLE_DATA: null
TEXT_ENCODER_TYPE: roberta
TRAIN_2D: false
TRAIN_3D: false
TRAIN_SUBSET_2D: null
TRAIN_SUBSET_3D: null
USE_GHOST_POINTS: false
USE_MLP_POSITIONAL_ENCODING: false
USE_SEGMENTS: false
USE_WANDB: false
VERSION: 2
VISUALIZE: true
VISUALIZE_3D: true
VISUALIZE_LOG_DIR: ./output/inference/visualizations
VISUALIZE_PRED: false
VIS_PERIOD: 0
WANDB_NAME: null
WARMUP_RATIO: 0.01
WEIGHT_TYING: false
